### ISSUE TITLE
VS 17 instead of VS Code

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/real-time-game-quiz-4ahif-JonasReichhardt#1]
Can i use VS 17 instead of VS Code?

I will use phaser.io and in my opinion working with phaser is easier in VS 17 than in Code.

**Comment by rstropek** [comment]
Absolutely no problem. Choose whatever development environment you prefer. As long as you fulfill the tech. requirements, everything is ok.

Greetings,
Rainer Stropek.
