### ISSUE TITLE
Physics of the player not working

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/real-time-game-quiz-4ahif-JonasReichhardt#2]
In my app.ts at line 64 im enabling physics for my player and a little bounce effect but when I test it the player is still falling through the ground.

**Comment by rstropek** [comment]
@JonasReichhardt  I think you are starting the game not correctly. I changed a few lines of code and tested it on my computer -> works now. Please let me know if that helps.

Regards,
Rainer Stropek.

**Comment by JonasReichhardt** [comment]
@rstropek Its working for me too. 

Thankfully,
Jonas Reichhardt

**Comment by rstropek** [comment]
Great. Glad that I could help.
