### ISSUE TITLE
Code not working after structuring

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/real-time-game-quiz-4ahif-JonasReichhardt#3]
I have structured my code into stages and added a menu but after the structuring the code isn't working anymore.

Error message:

> Uncaught ReferenceError: exports is not defined
    at app.js:2

**Comment by rstropek** [comment]
Hi @JonasReichhardt 

Good question, unfortunately there is no simple answer. You added imports (e.g. `import ... from "./boot"`) to *app.ts*. This code would work like a charm if it were running on the server-side (in Node.js). In your case, the code is running on the client-side (in the browser). Browsers do not understand `import` yet (to be more specific: [Recent versions of Chrome do](https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7) but you cannot expect module-support in browsers today).

If you want to use modules on the client-side, you have two options:

* Use a loader like [system.js](https://github.com/systemjs/systemjs)
* Use a bundler like [webpack](https://webpack.js.org/concepts/)
* Require the use of a rather new Chrome version and follow the [guidelines for ES6 modules in Chrome](https://medium.com/dev-channel/es6-modules-in-chrome-canary-m60-ba588dfb8ab7)

If you want to split your client-side code into modules, you have to dive into one of the solutions mentioned above. If that is too much effort for a single homework, I recommend keeping the game logic in a single file.

Hope this helps.

Greetings,
Rainer Stropek.

**Comment by JonasReichhardt** [comment]
@rstropek 

Thanks for the input. I will change it back as soon as possible.
