### ISSUE TITLE
VS Code version of the game isn't starting

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/real-time-game-quiz-4ahif-JonasReichhardt#4]
I've found a nice blog with an example of a Phaser.io game with VS Code and Typescript. I used his project structure but my source code and assets. The game shows his example but his code got deleted and I compiled the Typescript code into Javascript a number of times now.

Blog: _https://divillysausages.com/2015/06/09/using-phaser-with-visual-studio-code/_

**Comment by rstropek** [comment]
Thank your for sharing the link with me.

Greetings,
Rainer Stropek.
