### ISSUE TITLE
Update about the project

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/real-time-game-quiz-4ahif-JonasReichhardt#5]
Due to the facts that I was in hospital from 2nd to 4th of January for a surgery, the following days where I needed to rest and my ongoing influenza I have to admit that I'm be able to finish this project by any means.

I will try to make two players able to run around in the same world until the exam but I don't know when I recover from my influenza and can get work properly again.

I tried working on the game when I was in hospital but due to the medication, the new environment and the mental strain because it was my first surgery and not an easy one too I was unable to work on a satisfying level.

I hope it's understandable

With best regards,

Jonas Reichhardt

**Comment by rstropek** [comment]
Don't worry. The goal of the project is that you practice. If you cannot finish all features that you aimed for, that's fine. Working on the project is a good exercise for the exam next week.

Greetings,
Rainer Stropek.
