### ISSUE TITLE
Exam practice 

### ISSUE THREAD

**Issue by JonasReichhardt** [rstropek-teaching/real-time-game-quiz-4ahif-JonasReichhardt#6]
Dear @rstropek, 

I've started a Rock - Paper - Scissor implementation as practice but I'm stuck. 

Line 7 just don't want to find my HTML input element so the user is always a Guest. It seems like some DOM operations aren't working. 

Here is the link to the new repository: https://github.com/JonasReichhardt/RockPaperScissors

**Comment by rstropek** [comment]
Hi @JonasReichhardt 

I have downloaded your code and debugged it. I cannot reproduce your error. Line 7 works fine:
![image](https://user-images.githubusercontent.com/2341573/35084172-f66831ee-fc22-11e7-9946-157d0f4dd97d.png)

`playField` is set and points to the `div` element with the corresponding id.

Can you describe your problem in more details?

Greetings,
Rainer Stropek

**Comment by JonasReichhardt** [comment]
@rstropek 

I saw there was a missunderstanding I meant Line 7 in my client.ts not the Javascript file. I'm sorry that my description was lacking information.

In my client.ts in line 7 the HTML ELEMENT with the id UserInput is always null. The input field should be in the DOM because all other DOM operations are working fine.

Greetings,
Jonas Reichhardt

**Comment by rstropek** [comment]
Hmm, same thing. I tried your code and `userInput` is not null:

![image](https://user-images.githubusercontent.com/2341573/35211644-9c6e4f4c-ff57-11e7-951f-d182d590e152.png)

**Comment by JonasReichhardt** [comment]
@rstropek 

Ok I will try it on another notebook if it's still not working I will let it be.

Greetings,
Jonas Reichhardt
